name: treninoo
description: My first flutter project with Trenitalia API

version: 1.0.0+1
# android: 6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0+2
  # outline_material_icons: ^0.1.0
  shared_preferences: ^0.5.3+4
  flutter_typeahead: ^1.8.0
  url_launcher: ^5.5.0
  cupertino_icons: ^0.1.2
  provider: ^5.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  
flutter:
  uses-material-design: true

  assets:
    - assets/train_not_found.png

  fonts:
    - family: Cabin
      fonts:
        - asset: fonts/Cabin-Bold.ttf
        - asset: fonts/Cabin-Medium.ttf
        - asset: fonts/Cabin-Regular.ttf
        - asset: fonts/Cabin-SemiBold.ttf