name: treninoo
description: My first flutter project with Trenitalia API

version: 2.1.3+1
# android: 8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0+2
  shared_preferences: ^2.0.11
  flutter_typeahead: ^4.0.0
  cupertino_icons: ^0.1.2
  provider: ^6.0.3
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  intl: ^0.17.0
  firebase_core: ^1.10.6
  url_launcher: ^6.0.18
  adaptive_theme: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  
flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/train_not_found.png
    - assets/response/arrivi_milano.json
    - assets/response/partenze_milano.json

  fonts:
    - family: Cabin
      fonts:
        - asset: fonts/Cabin-Bold.ttf
        - asset: fonts/Cabin-Medium.ttf
        - asset: fonts/Cabin-Regular.ttf
        - asset: fonts/Cabin-SemiBold.ttf
