name: treninoo
description: My first flutter project with Trenitalia API

version: 1.0.0+1
# android: 8

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.0.11
  flutter_typeahead: ^4.0.0
  cupertino_icons: ^1.0.5
  provider: ^6.0.3
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  intl: ^0.17.0
  firebase_core: ^2.10.0
  url_launcher: ^6.0.18
  adaptive_theme: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  
flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/response/

  fonts:
    - family: Cabin
      fonts:
        - asset: fonts/Cabin-Bold.ttf
        - asset: fonts/Cabin-Medium.ttf
        - asset: fonts/Cabin-Regular.ttf
        - asset: fonts/Cabin-SemiBold.ttf
