/// Flutter icons TreninooIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TreninooIcon
///      fonts:
///       - asset: fonts/TreninooIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TreninooIcon {
  TreninooIcon._();

  static const _kFontFam = 'TreninooIcon';
  static const _kFontPkg = null;

  static const IconData treninoo_black_02_02 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
